services:

  backend:
    container_name: django
    build: .
    expose:
      - 8000
    volumes:
      - static_files:/app/static
      - media_files:/app/media
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - static_files:/app/static
      - media_files:/app/media

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

volumes:
  static_files:
  media_files: