# Generated by Django 5.0.6 on 2024-07-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_signature_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='signature',
            new_name='image',
        ),
        migrations.AddField(
            model_name='signature',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
