# Generated by Django 5.0.6 on 2024-07-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_rename_signature_signature_image_signature_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
