# Generated by Django 5.0.6 on 2024-07-06 00:44

import apps.signature.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0006_signature_image_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(upload_to=apps.signature.utils.signature_upload_path),
        ),
    ]
